version: 0.0
os: linux
files:
  - source: build
    destination: /home/ubuntu/backup
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/mv_build_file.sh
      timeout: 180
      runas: ubuntu
