name: Deploy to Front

on:
  push:
    branches:
      - main
    paths:
      - "front/**"

jobs:
  front_deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install node lts
        run: |
          nvm install --lts
          echo $(node --version)
