name: Deploy to Front

on:
  push:
    branches:
      - main
    paths:
      - "front/**"

jobs:
  front_deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install node lts
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install --lts

      - name: Install dependencies
        working-directory: front
        run: |
          npm install
          echo $(ls)
          echo $(pwd)

      - name: Build
        run: |
          echo $(ls)
          echo $(pwd)
